server:
  port: 9192

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pet_adoption_db
    username: root
    password: Meow@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
        ddl-auto: update
        format_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect    
  servlet:
    multipart:
    max-file-size: 10MB
    max-request-size: 5MB
    file-size-threshold: 2KB
